openapi: 3.0.2
info:
  version: '1.0'
  title: 'FDA Drug Label for Remdesivir'
  description: Drug Label Info for Remdesivir
  license:
    name: GNU General Public License v3 (GPL-3)
    url: >-
      https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /js/fda_label_content
    description: Hello world
tags:
  - name: KO Endpoints
    description: Hello world Endpoints
paths:
  /fda_label_content:
    post:
      parameters:
        - $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/parameters/apiversion'
      tags:
        - KO Endpoints
      description: Get FDA Drug Label content.
      operationId: fda_label_content
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericresponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericerror'
components:
  schemas:
    input:
      required:
        - id
      properties:
        name:
          type: string
          x-kgrid-label: 'Please enter a Question or Answer ID'
          x-kgrid-unit: ''
          example: '0'
